### ISSUE TITLE
Report is not public

### ISSUE THREAD

**Issue by xavigiro** [mcv-m6-video/mcv-m6-2022-team4#1]
The link to the report is to a restricted project on overleaf. Please create a PDF, upload it to the repo, and link it from your README.md. Toggle this issue as solved when you have finished.

**Comment by mv-lab** [comment]
https://www.overleaf.com/read/wsmjbmrrqpfn
link with edit permission (to see that we did not modify the document since the deadline): https://www.overleaf.com/4293243573mfxrpbwnmkrw

report added as pdf also in the repo.
Sorry for the inconvenience, the overleaf link was for editors, only works if the user is logged into overleaf.

**Comment by xavigiro** [comment]
All right, thanks. 

Please link from the README to the PDF in the Github repo, not to the overleaf.
